### PR TITLE
hera.gnu config & selective merge of UFS public release hotfix to develop (fixes problem with MPI_Comm_Split in openmpi when hash is negative)

### PR DESCRIPTION
**Pull request by climbfuji**
**See update in comment further down!**

This PR adds support for hera.gnu to the NEMS build system and merges two commits from the UFS public release branch to develop, required for using OpenMPI with the GNU compilers on Hera: 5434d8e86d35a859fbc0f983937ee1ae02b51812 and e84f1b9f30dfe4a68bf5c7443dfd365c66982892. See original PR https://github.com/NOAA-EMC/NEMS/pull/25 for the UFS public release branch (from @mark-a-potts).

Associated PRs:

https://github.com/NOAA-EMC/NEMS/pull/43
https://github.com/NCAR/ccpp-physics/pull/409
https://github.com/NCAR/fv3atm/pull/31
https://github.com/NCAR/ufs-weather-model/pull/28

For regression testing info, see https://github.com/NCAR/ufs-weather-model/pull/28.

This PR can be merged into develop without restriction, even though all associated PRs are going to NCAR's dtc/develop first (independent change), provided that the regression tests described above all pass.

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]
Approved.

**Comment by climbfuji** [comment]
Update 2020/03/17. This PR now needs to be merged as part of these PRs:

Associated PRs:

https://github.com/NOAA-EMC/NEMS/pull/43
https://github.com/NCAR/ccpp-physics/pull/410
https://github.com/NCAR/ccpp-framework/pull/268
https://github.com/NOAA-EMC/fv3atm/pull/81
https://github.com/ufs-community/ufs-weather-model/pull/84

See https://github.com/ufs-community/ufs-weather-model/pull/84 for regression testing information.

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA @RatkoVasic-NOAA @MinsukJi-NOAA

**Comment by junwang-noaa** [comment]
> @junwang-noaa @DusanJovic-NOAA @RatkoVasic-NOAA @MinsukJi-NOAA

I think this can be committed after full RT is done with ufs-weather-model PR

**Comment by MinsukJi-NOAA** [comment]
> > @junwang-noaa @DusanJovic-NOAA @RatkoVasic-NOAA @MinsukJi-NOAA
> 
> I think this can be committed after full RT is done with ufs-weather-model PR

Full RT (both NEMSCompsetRun and rt.sh) with ufs-weather-model PR (https://github.com/ufs-community/ufs-weather-model/pull/84) all passed on Hera:
[Compile_hera.intel.log](https://github.com/NOAA-EMC/NEMS/files/4346359/Compile_hera.intel.log)
[RegressionTests_hera.intel.log](https://github.com/NOAA-EMC/NEMS/files/4346362/RegressionTests_hera.intel.log)
[rtreport.txt](https://github.com/NOAA-EMC/NEMS/files/4346363/rtreport.txt)

**Comment by climbfuji** [comment]
Great, thank you! I also ran the rt.sh and NEMSCompsetRun tests on hera with Intel. I have already updated the rt.sh regression test logs in the PR, will update the NEMSCompsetRun logs in a minute. Thanks for doing this, highly appreciated.

**Pull request merged**
