### PR TITLE
Bugfix i2a & Add Orion to module-setup

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
This PR combines #57 and #60. Respective issues are #56 and #59 
Will add RT results.

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
S2S RT successfully passed on Orion: https://github.com/ufs-community/ufs-s2s-model/pull/88

**Review by DeniseWorthen — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
> S2S RT successfully passed on Orion: [ufs-community/ufs-s2s-model#88](https://github.com/ufs-community/ufs-s2s-model/pull/88)

Do we want to run RT on hera?

**Comment by MinsukJi-NOAA** [comment]
> > S2S RT successfully passed on Orion: [ufs-community/ufs-s2s-model#88](https://github.com/ufs-community/ufs-s2s-model/pull/88)
> 
> Do we want to run RT on hera?

I will add RT results on Hera

**Comment by MinsukJi-NOAA** [comment]
S2S RT successfully passed on Hera: ufs-community/ufs-s2s-model#88

**Review by DeniseWorthen — APPROVED** [review]

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Pull request merged**
