### PR TITLE
Update submodule pointer for NCEPLIBS-pyprodutil

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates the submodule pointer for NCEPLIBS-pyprodutil to point to the current head of the develop branch:
```
commit ca171b95095db4fcd0fc7b01c23d073d90becd99 (HEAD, origin/develop, origin/HEAD, develop)
Merge: 62561d2 1fc711d
Author: RatkoVasic-NOAA <37597874+RatkoVasic-NOAA@users.noreply.github.com>
Date:   Mon Mar 30 10:10:15 2020 -0400

    Merge pull request #5 from SamuelTrahanNOAA/slurm-label

    srun --label support: pass --label when label_io=True
```

Associated PRs:

https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/17
https://github.com/NCAR/ccpp-framework/pull/283
https://github.com/NCAR/ccpp-physics/pull/436
https://github.com/NOAA-EMC/fv3atm/pull/98
https://github.com/ufs-community/ufs-weather-model/pull/102

For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/102.

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@climbfuji, these changes were committed to NEMS already: https://github.com/NOAA-EMC/NEMS/commit/16e1b9423b7d66b89d1ff016ae2b20be743043af. Please let me know otherwise.

**Comment by climbfuji** [comment]
Sorry, this is so confusing. I checked out develop from NEMS, and I see that these changes are in. But what about the submodule pointer for pyprodutil? Which hash do you want me to use there? If I check out develop in NCEPLIBS-pyprodutil, I have
```
commit ca171b95095db4fcd0fc7b01c23d073d90becd99 (HEAD, origin/develop, origin/HEAD, develop)
Merge: 62561d2 1fc711d
Author: RatkoVasic-NOAA <37597874+RatkoVasic-NOAA@users.noreply.github.com>
Date:   Mon Mar 30 10:10:15 2020 -0400

    Merge pull request #5 from SamuelTrahanNOAA/slurm-label

    srun --label support: pass --label when label_io=True
```
but this hash is not the one that NEMS has at the moment. So at least I need to update that one (making this PR much more trivial, of course). @junwang-noaa

**Comment by climbfuji** [comment]
> Sorry, this is so confusing. I checked out develop from NEMS, and I see that these changes are in. But what about the submodule pointer for pyprodutil? Which hash do you want me to use there? If I check out develop in NCEPLIBS-pyprodutil, I have
> 
> ```
> commit ca171b95095db4fcd0fc7b01c23d073d90becd99 (HEAD, origin/develop, origin/HEAD, develop)
> Merge: 62561d2 1fc711d
> Author: RatkoVasic-NOAA <37597874+RatkoVasic-NOAA@users.noreply.github.com>
> Date:   Mon Mar 30 10:10:15 2020 -0400
> 
>     Merge pull request #5 from SamuelTrahanNOAA/slurm-label
> 
>     srun --label support: pass --label when label_io=True
> ```
> 
> but this hash is not the one that NEMS has at the moment. So at least I need to update that one (making this PR much more trivial, of course). @junwang-noaa

Ok, I think this is correct now.

**Comment by MinsukJi-NOAA** [comment]
You are right... Somehow pyprodutil has two identical commits: 1fc711dc021f08f5d1eda2f4b5108af43ae33ef7 & ca171b95095db4fcd0fc7b01c23d073d90becd99

**Comment by climbfuji** [comment]
Ok - the one I have now (ca171b9) is the head of develop.

**Comment by junwang-noaa** [comment]
> > Sorry, this is so confusing. I checked out develop from NEMS, and I see that these changes are in. But what about the submodule pointer for pyprodutil? Which hash do you want me to use there? If I check out develop in NCEPLIBS-pyprodutil, I have
> > ```
> > commit ca171b95095db4fcd0fc7b01c23d073d90becd99 (HEAD, origin/develop, origin/HEAD, develop)
> > Merge: 62561d2 1fc711d
> > Author: RatkoVasic-NOAA <37597874+RatkoVasic-NOAA@users.noreply.github.com>
> > Date:   Mon Mar 30 10:10:15 2020 -0400
> > 
> >     Merge pull request #5 from SamuelTrahanNOAA/slurm-label
> > 
> >     srun --label support: pass --label when label_io=True
> > ```
> > 
> > 
> > but this hash is not the one that NEMS has at the moment. So at least I need to update that one (making this PR much more trivial, of course). @junwang-noaa
> 
> Ok, I think this is correct now.

Actually I thought we only make s2 related code changes in ufs-weather-model side.  Anyway it's good if we update ufs-weather-model to the latest develop of prod-util. So now after we finish all the RT, we can ask Minsuk to commit.

**Comment by MinsukJi-NOAA** [comment]
I think we can merge this one because this was tested previously: https://github.com/NOAA-EMC/NEMS/pull/47. As mentioned above, pyprodutil 1fc711d (one that NEMS is currently pointing to) & ca171b9 (head of develop) are identical. @junwang-noaa @climbfuji please let me know.

**Pull request merged**
