### PR TITLE
NEMS driver cleanup

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Fixes issue #95

- The large number of line changes (>3000) in this PR is challenging. The commits were done stepwise:

c96dd29: remove NEMS mediator files
ac9558c: switch to yaml field dictionary, remove unused/legacy model fronts
8bbeb2a: remove ESMF<8 conditional blocks and code
ae01a66: clean up error logging
6f7ea44: simplify error messaging if required component is not found

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
Consider removing `module_NEMS_INTERNAL_STATE.F90`. It does not contain any useful state, just two dummy variables.

**Comment by DusanJovic-NOAA** [comment]
Now that we removed ensemble coupler there's no need to have both `NEMS` and `EARTH` components, one should be enough. Basically 'nems' should be just a main program and one grid component.

**Comment by DusanJovic-NOAA** [comment]
I also do not see where two variables in `EARTH_INTERNAL_STATE`:
```
        real(ESMF_KIND_R8)  :: medAtmCouplingIntervalSec
        real(ESMF_KIND_R8)  :: medOcnCouplingIntervalSec
```
are used. If they are not needed anymore, maybe `module_EARTH_INTERNAL_STATE.F90` can be removed as well.

**Comment by DeniseWorthen** [comment]
There will be one more PR to clean up the driver itself but I think removing the NEMS internal state file would be OK at this point.

**Comment by DusanJovic-NOAA** [comment]
Five subroutines from `module_NEMS_UTILS.F90` (`err_msg`, `err_msg_int`, `err_msg_val`, `err_msg_var` and `err_msg_final`) are also not used anywhere. `CHECK_ESMF_PET` can be moved to `MAIN_NEMS.F90`. Which basically means `module_NEMS_UTILS.F90` can be removed.

Functions `RTC()` and `TIMEF()` can be removed from `MAIN_NEMS.F90`

**Comment by DeniseWorthen** [comment]
I believe the check_esmf_pet functionality can be set using the [ESMF_LOG_KIND_MULTI](http://earthsystemmodeling.org/docs/release/ESMF_8_1_0/ESMF_refdoc/node6.html#const:logkindflag) and read from the nems.configure (instead of from model_configure). Then there will be nothing in the NEMS_UTILS that we need.

**Comment by DeniseWorthen** [comment]
I'm going to retain the ``NEMS_UTILS`` SR for now since I may want to move some items there in the second round.

I'm not sure what to do about the two ``INTERNAL_STATE`` SRs. I'm not confident enough of their purpose to actually remove them.

**Comment by DusanJovic-NOAA** [comment]
> I'm going to retain the `NEMS_UTILS` SR for now since I may want to move some items there in the second round.
> 
> I'm not sure what to do about the two `INTERNAL_STATE` SRs. I'm not confident enough of their purpose to actually remove them.

None of the variables from two internal states are used. They (internal states) can be removed.

**Comment by junwang-noaa** [comment]
I'd suggest to check with Mark Potts before removing the NEMS/earth internal state file. I am not sure if the JEDI-NEMS interface has been set up yet and if NEMS internal state will be used in that setting.

**Comment by DusanJovic-NOAA** [comment]
> I'd suggest to check with Mark Potts before removing the NEMS/earth internal state file. I am not sure if the JEDI-NEMS interface has been set up yet and if NEMS internal state will be used in that setting.

I do not see how and why would JEDI access to nems and earth internal states. As the name suggests they are internal. If JEDI needs anything from nems grid component it should access it via import and/or export states.

@mark-a-potts Can you please check if JEDI needs access to NEMS internal state.

**Comment by mark-a-potts** [comment]
> > I'd suggest to check with Mark Potts before removing the NEMS/earth internal state file. I am not sure if the JEDI-NEMS interface has been set up yet and if NEMS internal state will be used in that setting.
> 
> I do not see how and why would JEDI access to nems and earth internal states. As the name suggests they are internal. If JEDI needs anything from nems grid component it should access it via import and/or export states.
> 
> @mark-a-potts Can you please check if JEDI needs access to NEMS internal state.

The plan is for JEDI to get all information via NUOPC imports and exports, so it will not use the internal states.

**Comment by DeniseWorthen** [comment]
The ``EARTH_INTERNAL_STATE`` does appear to be used in the module_EARTH_GRID_COMP (``is%EARTH_INT_STATE``)?

**Comment by DusanJovic-NOAA** [comment]
> The `EARTH_INTERNAL_STATE` does appear to be used in the module_EARTH_GRID_COMP (`is%EARTH_INT_STATE`)?

EARTH_INTERNAL_STATE is declared, allocated, stored in the grid component and finally deallocated. But it's never actually used. Same for nems internal state. They can be removed.

**Comment by DusanJovic-NOAA** [comment]
Great. Now we just need to merge nems and earth component into one grid component, move check_esmf_pet to main program or use some alternative way of setting log type, figure out what to about these two rusage files and we'll be down to just main program and one grid component module. But that's for the next PR.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen is this pr ready for commit?

**Comment by DeniseWorthen** [comment]
Yes it is but we haven't been merging the subcomponent PRs until the ufs-weather is updated w/ the RTs. Did you want to merge it now?

**Comment by MinsukJi-NOAA** [comment]
@DeniseWorthen Yes let's wait for the ufs-weather RT results.

**Pull request merged**
