### PR TITLE
Feature/changefldnames

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Updates for 
issue #28 
issue #27 
issue #26
Issue #30 

The Atm/Ocn flux fields on atm grid have also been commented out in the prep_atm mediator phase since they are not used.

For the coupled model, this PR requires matching CICE and FV3 commits and the baselines will change due to the removal of the mediator fluxes in prep_ocn. Otherwise no baseline changes are expected.

The ability to build the CMEPS mediator is added to the module_EARTH_GRID_COMP.F90. Required build-related files are added.

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
Denise,
Do these changes affect s2s-model only? Do we need regression test results?

**Comment by DeniseWorthen** [comment]
Minsuk,

These should not affect the standalone.  Jun or Ratko could advise whether you need to test ufs-weather.

**Comment by RatkoVasic-NOAA** [comment]
> Minsuk,
> 
> These should not affect the standalone. Jun or Ratko could advise whether you need to test ufs-weather.

Minsuk, I suggest you run the ufs-weather test on Hera, just to make sure that nothing is broken.

**Comment by MinsukJi-NOAA** [comment]
Ufs-weather-model regression tests passed on hera:
[RegressionTests_hera.intel.log](https://github.com/NOAA-EMC/NEMS/files/4251049/RegressionTests_hera.intel.log)

> > Minsuk,
> > These should not affect the standalone. Jun or Ratko could advise whether you need to test ufs-weather.
> 
> Minsuk, I suggest you run the ufs-weather test on Hera, just to make sure that nothing is broken.

**Comment by MinsukJi-NOAA** [comment]
Ufs-s2s-model regression tests passed on hera:

[rtreport.txt](https://github.com/NOAA-EMC/NEMS/files/4261778/rtreport.txt)

**Comment by MinsukJi-NOAA** [comment]
Re-ran ufs-weather-model RT on hera due to additional changes (CMEPS mediator build capability). All tests passed.
[RegressionTests_hera.intel.log](https://github.com/NOAA-EMC/NEMS/files/4262052/RegressionTests_hera.intel.log)

**Review by MinsukJi-NOAA — APPROVED** [review]

**Pull request merged**
