### PR TITLE
NEMSCompsetRun bug fix: pass --label to srun (requires produtil PR)

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
The NEMSCompsetRun was asking produtil to pass the `--label` option, but that request was ignored since produtil.mpi_impl.srun_shell ignored the `label_io=True` option. This NCEPLIBS-pyprodutil PR fixes the bug in produtil. The submodule at the NEMS level must be updated as well:

- https://github.com/NOAA-EMC/NCEPLIBS-pyprodutil/pull/5

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@SamuelTrahanNOAA , can you please update this PR to include the latest NEMS and NCEPLIBS-pyprodutil changes? Thanks!

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA , can you please update this PR to include the latest NEMS and NCEPLIBS-pyprodutil changes? Thanks!

I merged the changes and I'm testing them now on Hera.

**Comment by SamuelTrahanNOAA** [comment]
@MinsukJi-NOAA The deed is done. I've merged the latest NEMS develop. I re-ran NEMSCompsetRun for the ufs-weather-model: all tests passed and the log file had the MPI rank at the beginning of each line.

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA The deed is done. I've merged the latest NEMS develop. I re-ran NEMSCompsetRun for the ufs-weather-model: all tests passed and the log file had the MPI rank at the beginning of each line.

Thanks! Merged the PR.

**Pull request merged**
