### PR TITLE
Remove cheyenne.intel-impi and supermuc_phase2.intel build targets

### PR DESCRIPTION
**Pull request by climbfuji**
As the title says.

Associated PRs:
https://github.com/NOAA-EMC/fv3atm/pull/150
https://github.com/NOAA-EMC/NEMS/pull/74
https://github.com/ufs-community/ufs-weather-model/pull/177

### CODE REVIEW

**Review by minsukji — APPROVED** [review]
looks good to me

**Comment by climbfuji** [comment]
> looks good to me

We need to get away from these `src/conf/module-setup.{sh,csh}.inc` files as soon as possible (cmake build?)

**Review by MinsukJi-NOAA — APPROVED** [review]
Changes look good. I apologize for mixing up my personal github account in the previous review

**Comment by climbfuji** [comment]
> Changes look good. I apologize for mixing up my personal github account in the previous review

No worries, happens way too often to me, too.

**Pull request merged**
