### PR TITLE
add cime_config to NEMS model

### PR DESCRIPTION
**Pull request by jedwards4b**
Directory and files needed for the CIME interface.  These files have no affect on NEMS if cime is not used.  See issue: https://github.com/ufs-community/ufs-mrweather-app/issues/14

### CODE REVIEW

**Comment by RatkoVasic-NOAA** [comment]
@jedwards4b 
is there any reason you cannot keep this inside CIME workflow? We have many workflows here and it is not recommended to keep workflow stuff inside NEMS.
-Ratko

**Comment by mvertens** [comment]
@RatkoVasic-NOAA  - this is needed outside of the  CIME workflow. This directory contains the API for components to be CIME compliant and as a result it belongs with the components not with CIME. Since CIME has been decided on to be the supported workflow for the release - this needs to come into the NEMS directory structure.

**Comment by mvertens** [comment]
@RatkoVasic-NOAA @rsdunlapiv - would it be useful to have a quick call to discuss this?

**Comment by RatkoVasic-NOAA** [comment]
@mvertens,  Arun will be back tomorrow, we have to discuss this internally first.

**Comment by mvertens** [comment]
@Ratko Vasic <Ratko.Vasic@noaa.gov> @rsdunlapiv -   sounds good. I'm fine
having a call as well if that would be helpful.

**Pull request closed without merging**
