### PR TITLE
set total forecast time to be real

### PR DESCRIPTION
**Pull request by junwang-noaa**
Set total forecast time to be real number to allow flexible forecast time

Related PRs:

[fv3 PR #175](https://github.com/NOAA-EMC/fv3atm/pull/175)
[NEMS PR #81](https://github.com/NOAA-EMC/NEMS/pull/81)
[ufs-weather-model PR #206](https://github.com/ufs-community/ufs-weather-model/pull/206)

### CODE REVIEW

**Comment by climbfuji** [comment]
Thanks! This change has been overdue.

**Review by climbfuji — APPROVED** [review]
I haven't tested it, but it looks ok to me.

**Comment by junwang-noaa** [comment]
Dom, thanks for reviewing it. We need to test this branch for LAM and HAFS
to confirm it works for high resolution runs before we run RT and commit
the code.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
@junwang-noaa, Is this PR ready for merge?

**Comment by junwang-noaa** [comment]
Minsuk,

I am running RT, it is supposed to be committed with ufs-weather-model PR
#206.

**Comment by junwang-noaa** [comment]
Minsuk,  All the RTs are done. You can merge the PR. Thanks

**Pull request merged**
