### PR TITLE
Build NEMS on S4

### PR DESCRIPTION
**Pull request by aerorahul**
Build NEMS on SSEC University of Wisconsin S4 supercomputer.

See corresponding [UFS PR #98](https://github.com/ufs-community/ufs-weather-model/pull/98)

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by junwang-noaa** [comment]
The changes are good, NEMS code manager Minsuk will do a final check and he
can commit the code. On ufs-weather-model side,  *@DusanJovic-NOAA*, do you
think we can combine this with Tom's commit?

**Comment by DusanJovic-NOAA** [comment]
All regression test log files for Tom's commit are already uploaded. If we ask him to update NEMS we'll need to rerun full tests on all platforms.

**Comment by junwang-noaa** [comment]
I thought Tom made code changes following Rusty's suggestion in code review.

**Comment by DusanJovic-NOAA** [comment]
I didn't see any commits made to https://github.com/TomBlack-NOAA/GFDL_atmos_cubed_sphere/tree/blend_DA

**Pull request merged**
