### PR TITLE
Bugfix for issue "NEMS hash 044400a8eea19d1ce991a2adaa0b369ed0e067c7 and head of develop broken for GNU compilers"

### PR DESCRIPTION
**Pull request by climbfuji**
src/module_EARTH_GRID_COMP.F90: bugfix for GNU compiler, lengths of strings have to match

see https://github.com/NOAA-EMC/NEMS/issues/41

This compiles with gcc/gfortran on macOS.

Note: this PR was created on top of hash 044400a8eea19d1ce991a2adaa0b369ed0e067c7, which is used by the ufs-weather-model; the head of develop seem to have advanced beyond this.

### CODE REVIEW

**Review by RatkoVasic-NOAA — COMMENTED** [review]
Looks good to me.
Minsuk Ji should approve this PR.

**Comment by climbfuji** [comment]
Thanks! Fixing the bug in ufs-weather-model after merging this PR will require updating the hash to the top of develop in ufs-weather-model (I am currently updating the PR and testing it with ufs-weather-model).

**Comment by MinsukJi-NOAA** [comment]
> Thanks! Fixing the bug in ufs-weather-model after merging this PR will require updating the hash to the top of develop in ufs-weather-model (I am currently updating the PR and testing it with ufs-weather-model).

Let me know how the testing goes. I will merge the PR. Thanks!

**Comment by climbfuji** [comment]
I updated this PR and merged the develop branch in, then ran the tests on hera for the ufs-weather-model (`rt.sh`) and the tests all pass. You can merge this PR from my side.

**Pull request merged**
