### PR TITLE
Add data ocean support and add support for reading modelio:: attribute group ...

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to bring data ocean support to NEMS, which is related to the issue https://github.com/NOAA-EMC/NEMS/issues/107. It also includes fix for reading modelio attributes from nems.configure and passing it to the CDEPS and CMEPS in case of it is defined.

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]

**Review by binli2337 — APPROVED** [review]

**Comment by MinsukJi-NOAA** [comment]
I ran UFS-weather-model regression tests with this NEMS changes on Hera. All gnu passed. All intel passed except for control_atm_aerosols, which resulted in MPI_Abort. Tried it 4 times and all failed. Can any one try this test case on Hera and verify?

**Comment by uturuncoglu** [comment]
@MinsukJi-NOAA i am not sure but this could be an issue related with recently added GOCART chemistry component.

**Comment by junwang-noaa** [comment]
@MinsukJi-NOAA where is your RT run directory with the failed  control_atm_aerosols test?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA where is your RT run directory with the failed control_atm_aerosols test?

LOGDIR: /scratch2/NCEPDEV/stmp1/Minsuk.Ji/ufs-weather-model/tests/log_hera.intel

RUNDIR: /scratch1/NCEPDEV/stmp2/Minsuk.Ji/FV3_RT/rt_64975/control_atm_aerosols

**Comment by DeniseWorthen** [comment]
The PET000 log shows ``PET000 module_EARTH_GRID_COMP.F90:453 Not valid  -  No component gocart found``. I think the branch needs to be updated w/ the current head of NEMS.

**Comment by MinsukJi-NOAA** [comment]
> The PET000 log shows `PET000 module_EARTH_GRID_COMP.F90:453 Not valid - No component gocart found`. I think the branch needs to be updated w/ the current head of NEMS.

I think you are right. #102 was merged in after this PR was submitted.

**Comment by junwang-noaa** [comment]
Yes, there is no gocart in module_EARTH_GRID_COMP.F90. @uturuncoglu please merge with the latest nems develop branch.

[Jun.Wang@hfe11 src]$ grep -i "gocart" module_EARTH_GRID_COMP.F90
[Jun.Wang@hfe11 src]$

**Comment by BinLiu-NOAA** [comment]
@junwang-noaa @MinsukJi-NOAA @DeniseWorthen @uturuncoglu, I have just synced this feature/hafs_couplehycom_cdeps branch with the latest develop branch.

**Comment by MinsukJi-NOAA** [comment]
control_atm_aerosols regression test passed. This PR is good for merge into UFS-weather-model @junwang-noaa @DeniseWorthen

**Comment by junwang-noaa** [comment]
@DeniseWorthen <https://github.com/DeniseWorthen> can we merge this PR
with your ufs-weather-model PR #639?

**Comment by DeniseWorthen** [comment]
Yes that would be fine. I will switch my .gitmodules to point to the PR branch.

**Comment by MinsukJi-NOAA** [comment]
@BinLiu-NOAA #104 is expected to be merged in today. Please update the feature/hafs_couplehycom_cdeps branch once again after that since this PR is scheduled for early next week.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA #104 is expected to be merged in today. Please update the feature/hafs_couplehycom_cdeps branch once again after that since this PR is scheduled for early next week.

Will do. Thanks @MinsukJi-NOAA!

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA Could you please update to the NEMS commit from today? Thanks.

**Comment by BinLiu-NOAA** [comment]
@MinsukJi-NOAA @DeniseWorthen, have just synced with the latest develop branch as of this afternoon (07/16/2021). Thanks!

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
